# Generated by Django 5.1.4 on 2025-01-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_exercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='title',
            new_name='option1',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='content',
        ),
        migrations.AddField(
            model_name='exercise',
            name='correct_answer',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], default='Default Question', help_text='Select the correct option', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='option2',
            field=models.CharField(default='Option 2', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='option3',
            field=models.CharField(default='Option 2', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='option4',
            field=models.CharField(default='Option 2', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='question',
            field=models.CharField(default='Default Question', max_length=500),
        ),
    ]
